//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventss
    {
        public int enents_id { get; set; }
        public string events_name { get; set; }
        public string event_date { get; set; }
        public string event_time { get; set; }
        public string event_day { get; set; }
    }
}
