//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smssystemEntities1 : DbContext
    {
        public smssystemEntities1()
            : base("name=smssystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<atten_april> atten_april { get; set; }
        public virtual DbSet<atten_aug> atten_aug { get; set; }
        public virtual DbSet<atten_dec> atten_dec { get; set; }
        public virtual DbSet<atten_feb> atten_feb { get; set; }
        public virtual DbSet<atten_January> atten_January { get; set; }
        public virtual DbSet<atten_July> atten_July { get; set; }
        public virtual DbSet<atten_June> atten_June { get; set; }
        public virtual DbSet<atten_march> atten_march { get; set; }
        public virtual DbSet<atten_may> atten_may { get; set; }
        public virtual DbSet<atten_nov> atten_nov { get; set; }
        public virtual DbSet<atten_oct> atten_oct { get; set; }
        public virtual DbSet<atten_sep> atten_sep { get; set; }
        public virtual DbSet<classI_courses> classI_courses { get; set; }
        public virtual DbSet<classII_courses> classII_courses { get; set; }
        public virtual DbSet<classIII_courses> classIII_courses { get; set; }
        public virtual DbSet<classIV_courses> classIV_courses { get; set; }
        public virtual DbSet<classV_courses> classV_courses { get; set; }
        public virtual DbSet<eventss> eventsses { get; set; }
        public virtual DbSet<fee_Amount_April> fee_Amount_April { get; set; }
        public virtual DbSet<fee_Amount_Augest> fee_Amount_Augest { get; set; }
        public virtual DbSet<fee_Amount_December> fee_Amount_December { get; set; }
        public virtual DbSet<fee_Amount_February> fee_Amount_February { get; set; }
        public virtual DbSet<fee_Amount_January> fee_Amount_January { get; set; }
        public virtual DbSet<fee_Amount_July> fee_Amount_July { get; set; }
        public virtual DbSet<fee_Amount_June> fee_Amount_June { get; set; }
        public virtual DbSet<fee_Amount_march> fee_Amount_march { get; set; }
        public virtual DbSet<fee_Amount_May> fee_Amount_May { get; set; }
        public virtual DbSet<fee_Amount_November> fee_Amount_November { get; set; }
        public virtual DbSet<fee_Amount_Octuber> fee_Amount_Octuber { get; set; }
        public virtual DbSet<fee_Amount_September> fee_Amount_September { get; set; }
        public virtual DbSet<IX_courses> IX_courses { get; set; }
        public virtual DbSet<playgroup_courses> playgroup_courses { get; set; }
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_enrolment> tbl_enrolment { get; set; }
        public virtual DbSet<tbl_registration> tbl_registration { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<timetable> timetables { get; set; }
        public virtual DbSet<VI_courses> VI_courses { get; set; }
        public virtual DbSet<VII_courses> VII_courses { get; set; }
        public virtual DbSet<VIII_courses> VIII_courses { get; set; }
        public virtual DbSet<X_courses> X_courses { get; set; }
    }
}
