//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_registration
    {
        public int Stu_reg_id { get; set; }
        public string Stu_f_name { get; set; }
        public string Stu_l_name { get; set; }
        public string Stu_father_name { get; set; }
        public string stu_father_cnic { get; set; }
        public string stu_nationality { get; set; }
        public string stu_reg_date { get; set; }
        public string Stu_gender { get; set; }
        public string Stu_address { get; set; }
        public string stu_contact { get; set; }
        public string stu_A_Contact { get; set; }
        public string stu_date_of_birth { get; set; }
        public string Stu_religion { get; set; }
        public string stu_class { get; set; }
    }
}
