//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_enrolment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_enrolment()
        {
            this.atten_april = new HashSet<atten_april>();
            this.atten_aug = new HashSet<atten_aug>();
            this.atten_dec = new HashSet<atten_dec>();
            this.atten_feb = new HashSet<atten_feb>();
            this.atten_January = new HashSet<atten_January>();
            this.atten_July = new HashSet<atten_July>();
            this.atten_June = new HashSet<atten_June>();
            this.atten_march = new HashSet<atten_march>();
            this.atten_may = new HashSet<atten_may>();
            this.atten_nov = new HashSet<atten_nov>();
            this.atten_oct = new HashSet<atten_oct>();
            this.atten_sep = new HashSet<atten_sep>();
            this.fee_Amount_April = new HashSet<fee_Amount_April>();
            this.fee_Amount_Augest = new HashSet<fee_Amount_Augest>();
            this.fee_Amount_December = new HashSet<fee_Amount_December>();
            this.fee_Amount_February = new HashSet<fee_Amount_February>();
            this.fee_Amount_January = new HashSet<fee_Amount_January>();
            this.fee_Amount_July = new HashSet<fee_Amount_July>();
            this.fee_Amount_June = new HashSet<fee_Amount_June>();
            this.fee_Amount_march = new HashSet<fee_Amount_march>();
            this.fee_Amount_May = new HashSet<fee_Amount_May>();
            this.fee_Amount_November = new HashSet<fee_Amount_November>();
            this.fee_Amount_Octuber = new HashSet<fee_Amount_Octuber>();
            this.fee_Amount_September = new HashSet<fee_Amount_September>();
        }
    
        public int Stu_id { get; set; }
        public string Stu_f_name { get; set; }
        public string Stu_l_name { get; set; }
        public string Stu_father_name { get; set; }
        public string Stu_father_mobile_Number { get; set; }
        public string Stu_father_cnic { get; set; }
        public string Stu_religion { get; set; }
        public string Stu_gender { get; set; }
        public string Stu_contact { get; set; }
        public string Stu_address { get; set; }
        public string Stu_date_of_birth { get; set; }
        public string Stu_nationality { get; set; }
        public string Stu_birth_place { get; set; }
        public string Stu_Emergency_contact { get; set; }
        public string Stu_city { get; set; }
        public string Stu_email_address { get; set; }
        public string Stu_country { get; set; }
        public string Stu_class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_april> atten_april { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_aug> atten_aug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_dec> atten_dec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_feb> atten_feb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_January> atten_January { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_July> atten_July { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_June> atten_June { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_march> atten_march { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_may> atten_may { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_nov> atten_nov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_oct> atten_oct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atten_sep> atten_sep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_April> fee_Amount_April { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_Augest> fee_Amount_Augest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_December> fee_Amount_December { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_February> fee_Amount_February { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_January> fee_Amount_January { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_July> fee_Amount_July { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_June> fee_Amount_June { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_march> fee_Amount_march { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_May> fee_Amount_May { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_November> fee_Amount_November { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_Octuber> fee_Amount_Octuber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee_Amount_September> fee_Amount_September { get; set; }
    }
}
