//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int teacher_id { get; set; }
        public string teacher_name { get; set; }
        public string Teacherjoin_date { get; set; }
        public string Qualification { get; set; }
        public string Teaching_course { get; set; }
        public string teacher_contact { get; set; }
        public string teacher_monthly_salary { get; set; }
    }
}
