//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int table_id { get; set; }
        public string table_day { get; set; }
        public string table_session1 { get; set; }
        public string table_session2 { get; set; }
        public string table_session3 { get; set; }
        public string table_session4 { get; set; }
        public string table_session5 { get; set; }
        public string table_session6 { get; set; }
        public string table_session7 { get; set; }
        public string table_session8 { get; set; }
    }
}
